# Generated by Django 4.0.4 on 2023-01-19 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('tosend', models.CharField(max_length=50)),
                ('chat', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 1, 19, 15, 49, 12, 724690))),
            ],
        ),
    ]
