# Generated by Django 4.0.4 on 2023-01-19 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 16, 42, 6, 877747)),
        ),
    ]
