# Generated by Django 4.0.4 on 2023-01-23 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chat_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 11, 13, 30, 287215)),
        ),
    ]
