# Generated by Django 4.0.4 on 2023-01-25 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chat_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 15, 24, 12, 740080)),
        ),
    ]
