# Generated by Django 4.0.4 on 2023-01-25 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chat_room_alter_chat_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='tosend',
        ),
        migrations.AlterField(
            model_name='chat',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 15, 37, 20, 452154)),
        ),
    ]
