# Generated by Django 4.0.4 on 2023-01-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('mothertoug', models.CharField(max_length=30)),
                ('reigion', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
