# Generated by Django 4.0.4 on 2023-01-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='image',
            field=models.ImageField(default=1, upload_to='static/'),
            preserve_default=False,
        ),
    ]
