# Generated by Django 4.0.4 on 2023-01-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cuser_password_cuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='image',
            field=models.ImageField(upload_to='static/client/'),
        ),
    ]
