# Generated by Django 4.0.4 on 2023-01-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
