# Generated by Django 4.0.4 on 2023-01-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_cuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuser',
            options={},
        ),
    ]
