# Generated by Django 4.0.4 on 2023-01-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_cuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='country',
        ),
    ]
