# Generated by Django 4.0.4 on 2023-01-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_cuser_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='date',
        ),
        migrations.AlterField(
            model_name='cuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
