# Generated by Django 4.0.4 on 2023-01-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_cuser_date_alter_cuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
