# Generated by Django 4.0.4 on 2023-01-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_cuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('touser', models.CharField(max_length=30)),
                ('request', models.BooleanField()),
                ('room', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
